import = [
  "~/.config/alacritty/themes/themes/catppuccin.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.7
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"
bold.family = "MesloLGS Nerd Font Mono"
italic.family = "MesloLGS Nerd Font Mono"
# normal.family = "MesloLGS Nerd Font Mono"

size = 14

[keyboard]
bindings = [
	{ key = "Right", mods = "Alt", chars = "\u001BF" },
	{ key = "Left", mods = "Alt", chars = "\u001BB" },
	{ key = "F", mods = "Alt", action = "ToggleSimpleFullscreen" },
	{ key = "Q", mods = "Command", action = "None" },
]
